# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o socket-server ./cmd/socket/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/socket-server ./socket-server
EXPOSE 8081
CMD ["./socket-server"] 