# syntax=docker/dockerfile:1
FROM golang:1.24.3-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod tidy
COPY . .
RUN go build -o socket-server ./cmd/socket/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/socket-server ./socket-server
EXPOSE 8081
CMD ["./socket-server"] 